### ISSUE TITLE
How to handle multiple clients with different default pages?

### ISSUE THREAD

**Issue by mouth4war** [resoai/TileBoard#137]
For discussion, I want to know how people are handling multiple clients and default pages for each client. 

I have 3 tablets in different rooms running fully kiosk pointing to the same TB index.html hosted on the HASS server www folder (I had different local instances earlier). I want each tablet to have a different default page (each room has a page defined in TB).

Ideally, if I could specify the page using a URL parameter, that would be an easy solution. Each kiosk would have a different URL then.

**Comment by cgarwood** [comment]
I have a separate pages variable with entries for each tablet (as well as a default and a global). I then use the `fully.getDeviceId()` function to return a unique ID for each tablet, and inject the correct pages variable into `CONFIG.pages`.

```
if (typeof PAGES[deviceId] === 'undefined') { CONFIG['pages'] = PAGES['default']; } else { CONFIG['pages'] = PAGES[deviceId]; }
CONFIG['pages'] = CONFIG['pages'].concat(PAGES['global']);
```

I may change it though, because this makes it impossible to debug on a different tablet since they're tied to the tablet's device id.

**Comment by resoai** [comment]
https://github.com/resoai/TileBoard/wiki/Mobile-configuration#how-do-i-divide-configs-on-mobile-and-non-mobile
