### ISSUE TITLE
Feature Request: add alarm_control_panel.ha_alarm

### ISSUE THREAD

**Issue by nayaj** [resoai/TileBoard#20]
Would be nice if [](https://www.home-assistant.io/components/alarm_control_panel.manual/) support could be added.

here is a popup example from what is expected when clicked in regular Hassio GUI.

![2018-06-21 09-00-06](https://user-images.githubusercontent.com/40382766/41702771-9383f18e-7531-11e8-81fe-0228365bfd9a.jpg)

**Comment by resoai** [comment]
It is a bit more complicated since we will also need a popup for entering security code etc. This is something which we could implement at later stage unless someone wishes to take a lead and implement it. As a quick workaround for now you could use two switch tiles (one for arming home and one for arming away) and have a simple automation in HA. 

I myself have an alarm component in my HA and am currently using a generic icon to simply display the status.

**Comment by syphernl** [comment]
For entering security codes something like like [this](https://www.cssscript.com/demo/ios-style-pin-code-validation-with-javascript-and-css3/) would be awesome to have :slightly_smiling_face: 

The correct code is `1593` if you want to try.

**Comment by nayaj** [comment]
I am.

Solved it for now by using an input select menu and automations and sensors.

**Comment by resoai** [comment]
@nayaj you have no code set up for the alarm panel, right? Would you be able to post state dump?

**Comment by freekeys** [comment]
Any more thoughts on the keypad entry? This would be so great! 

@nayaj are you using input selects to enter an alarm code?

**Comment by resoai** [comment]
As I mentioned above, ALARM tile has been implemented along with the keypad.
