### ISSUE TITLE
Feature Request: Screensaver

### ISSUE THREAD

**Issue by cgarwood** [resoai/TileBoard#4]
Add a screensaver option. After x seconds of inactivity, switch to essentially a digital picture frame with a clock and possibly weather overlay. Tapping on the screen would take you back to either the main dashboard or the previous dashboard.

I hacked this in to my HADashboard install and it looked like this:
![img_2923](https://user-images.githubusercontent.com/7545841/41607399-f4c9ed60-73b3-11e8-882f-a36fa94947ad.JPG)

Feed it a JSON list of pictures and it will loop through them every 5s or so. I did end up adding a full-screen weather slide at the beginning of the loop as well (that hides the big clock overlay) that includes the current weather conditions and forecast for the next couple days. I had issues with image retention on the Kindle Fire 8" screens where you'd see a faint outline of the clock. Adding the full-screen weather slide that hid the clock helped quite a bit with that.

I'm willing to share code or help program it in, but I've never worked with Angular before, so that will be a bit of a learning curve.

**Comment by oakbrad** [comment]
Fully Kiosk Browser app has this feature, I use it on my Kindle Fire. The screensaver can be set to any URL.

**Comment by cgarwood** [comment]
I use that feature on Fully too, but with dim: so it essentially turns the screen off. FireOS won’t let you actually turn the screen on and off from fully without giving you the lock screen :(

**Comment by resoai** [comment]
To be frank keeping the screen on all the time will eventually just burn the screen and drain power. Although it would be somewhat nice to use it as a digital frame, I myself still prefer for the screen to turn on automatically when there is motion i.e. the king of castle approaches the screen :) This also has yet another benefit as you can simply glance at a screen even at a distance rather than having to come to it, make a gesture to unlock it.

**Comment by resoai** [comment]
I might be wrong, but I think there are LineageOS builds (official) for Fire tablets.

**Comment by resoai** [comment]
Let's leave screensaver task to Fully Kiosk Browser app.
