### ISSUE TITLE
Commitlint on master only?

### ISSUE THREAD

**Issue by akloeckner** [resoai/TileBoard#444]
See #443 

> Something wrong on my side, or did you forget to commit a file?

Maybe linting commit messages should also be done on master, only?

**Comment by akloeckner** [comment]
@rchl not sure, if you get this by default, hence the mention...

**Comment by rchl** [comment]
I've replied about your issue there.

Doing the check on master only won't work since that would not run when merging PRs so badly formatted commit messages would sneak in that way.

We could have a GitHub check running in PRs to lint commit messages but I think that wouldn't work very well either as the branch would have to be rewritten to fix them and rewriting doing review is not friendly to reviewers.

What's the issue with it for you? The problem you've reported is likely due to 'npm i' not having been run.

Otherwise it shouldn't be much of a problem to format your commits in certain way.

**Comment by akloeckner** [comment]
It's just a bit strange to commit *every* message with a `feat` tag or the like. (Although only one single smashed commit will make it into the master branch in the end.) I'll be forced to apply those conventios to *all* my local branches, even those that will never be made public. And in my personal history, they seem to create quite some clutter... 

I thought, I'd better try to help and put thing right in the first place. If there's no reasonale technical way, I'll try to follow the conventions and see how much of a hassle it is in real life.

**Comment by rchl** [comment]
That's a good point. I do make throwaway commit messages all the times in PRs, knowing that all will be squashed before merging.

I'll look into it more.

**Comment by rchl** [comment]
Disabled commit linting until I figure out a better solution.

**Comment by akloeckner** [comment]
Sure! It's good to discuss things. Makes the issues also clearer to me. And sometimes even solves them rightaway. 👍
