### ISSUE TITLE
Empty mode button

### ISSUE THREAD

**Issue by yadenisenko** [resoai/TileBoard#531]
Hello,
I am install TileBoard v2.0.3 and Home Assistant last version(0.117.6).
I am create tile following example, but the field where the mode selection button should be is empty.
I can press it and turn on the air conditioner, but I never see the current status,
Help me please, my current tile:
`				  {
   position: [0, 1],
   width: 2,
   id: "climate.air_conditioner_2",
   type: TYPES.CLIMATE,
   unit: 'C',
   useHvacMode: true,  // Optional: enables HVAC mode (by default uses PRESET mode)
   state:
   function (item, entity) {
      return 'Current '
         + entity.attributes.current_temperature
         + " °C";
   }
}`

![1](https://user-images.githubusercontent.com/15608867/99680169-d0657f00-2a8d-11eb-977b-2bb4f19157ad.jpg)
![2](https://user-images.githubusercontent.com/15608867/99680173-d0fe1580-2a8d-11eb-95b9-b70b7b763e4e.jpg)

**Comment by resoai** [comment]
Please post state dump for this entity from Developer tools -> States in HA.

**Comment by yadenisenko** [comment]
hvac_modes: off, heat, cool, heat_cool, dry, fan_only
min_temp: 17
max_temp: 30
target_temp_step: 1
fan_modes: low, mid, high, auto
current_temperature: 30
temperature: 25
current_humidity: 28
fan_mode: mid
last_on_operation: fan_only
device_code: 1660
manufacturer: ROYAL
supported_models: 08HPN1T1
supported_controller: Broadlink
commands_encoding: Base64
friendly_name: Кондиционер
supported_features: 9

**Comment by resoai** [comment]
It looks like your device has `hvac_modes` list yet no `hvac_mode` which is the attribute responsible for outputting current vac mode. For some reason it is in `last_on_operation` if I understand correctly. I'm not an expert but this might be because it is an IR controlled device and there is no feedback from it, so if the mode is charged from another remote, HA will have no idea that it was done.

How does it show up in HA?

**Comment by yadenisenko** [comment]
The search led me to https://github.com/resoai/TileBoard/issues/526 and the fix suggested there displayed the current value in the switch:
![1](https://user-images.githubusercontent.com/15608867/99690726-81bde200-2a99-11eb-9659-887126b2ab70.jpg)
HA do not have problem, I can switch all modes, change temperature and fan speed.
![1](https://user-images.githubusercontent.com/15608867/99689864-87ff8e80-2a98-11eb-86e2-dbce5a30e02d.jpg)
![2](https://user-images.githubusercontent.com/15608867/99689869-8930bb80-2a98-11eb-982a-b7675fe6dd7b.jpg)

Now it remains to teach the tile to switch the fan speed. Do you have any ideas? 😄

**Comment by rchl** [comment]
@yadenisenko in your last comment you've shown a screenshot of tileboard tile and HA card. Are those made at the same time. Because TileBoard tile says the state is `off` while the HA card says that it's `cooling` (according to my limited knowledge of Russian). So are those screenshots taken at different times or the state in TileBoard is not correct?

**Comment by yadenisenko** [comment]
Hello, @rchl . Screenshot's were made at different times.
If I turn on the AC in ON the HA card, then the changes are displayed same in the TileBoard

**Comment by rchl** [comment]
Should be fixed in https://github.com/resoai/TileBoard/releases/tag/v2.1.0

Also, the value of the `hvac_action` attribute will be shown as a "subtitle". You haven't shown it in your attributes dump but I think it will exist when it's cooling or warming at the moment. At least it seems so from the HA card.
