### ISSUE TITLE
Page header

### ISSUE THREAD

**Issue by Evgeny-** [resoai/TileBoard#92]
Current header isn't perfect, isn't really customizable. Sure there is an option to create own html file, but it isn't userfriendly. 
My thought on header: it should has:
* Date and time
* Customizable weather
* Custom string line (like state of anything)

Your thoughts?

**Comment by resoai** [comment]
I agree. Perhaps the same directives could also be applied to screensaver overlay should people decide to customize it.

**Comment by cgarwood** [comment]
Sounds good. Would be nice to be able to persist it across pages so it doesn't "scroll" when you change pages if that's possible.

Some sort of weather alert support would be good too. Maybe we could use the "custom string" option for that. Was thinking something like this, though I drew it in the footer instead of the header:
![tileboard-weather-alert](https://user-images.githubusercontent.com/7545841/42758047-18be4bd6-88d0-11e8-95a0-9530c4c2922a.png)

**Comment by Evgeny-** [comment]
Isn't noties good for weather alerts?
